fix typo in sample arm template of managed identity
If the wrong sample snippet is copied and used in arm template, it can cause some error in deployment like below:

Error: Code=InvalidIdentityId; Message=The identity ids '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-xxx/providers/Micrososft.ManagedIdentity/userAssignedIdentities/MSI_xxxx' are invalid. It must be of the following format: '/subscriptions/{
subscriptionId
}/resourceGroups/{
resourceGroupName
}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{
resourceName
}'.

It is tricky to spot such kind of bug.