Update use-azure-ad-pod-identity.md
I tried without azure network plugin and got the following error:
```
BadRequestError: Operation failed with status: 'Bad Request'. Details: Network plugin kubenet is not supported to use with PodIdentity addon.
```
Hence adding the network-plugin parameter to this documentation.