Fix "-e" option for "azure network net create".
Command line option should use "-"(ASCII: 0x2d) instead of "-"(Unicode: 0x2013: Em-Dash).
This causes following error when  this script is copied and pasted to command line.

	info:    Executing command network vnet create
	error:   The name can contain only letters, numbers and hyphens with no more than 63 characters. It must start with a letter or number