Update troubleshoot-synapse-studio.md
Symptom
 
If your Synapse Studio session becomes idle for a large period of time (>30m) the publish operation may fail throwing this error message:
 
ERROR: Unauthorized Inner error code: ExpiredAuthenticationToken Message: Token Authentication failed with SecurityTokenExpiredException - MISE12034: AuthenticationTicketProvider Name:AuthenticationTicketProvider, GetVersion:1.9.2.0.;
 
Root Cause and mitigation:
You should avoid long periods of inactivity in Synapse Studio, specially in scenarios where your network conditions are restricting the usage of the http2 protocol.