Update kubernetes-helm.md
Add link to new location for helm, 
gary_ciampa@Azure:~/source$ helm repo add stable https://kubernetes-charts.storage.googleapis.com/
Error: repo "https://kubernetes-charts.storage.googleapis.com/" is no longer available; try "https://charts.helm.sh/stable" instead
gary_ciampa@Azure:~/source$ helm repo add stable  "https://charts.helm.sh/stable"
"stable" has been added to your repositories