Update concepts-audit.md
If this new step is missing, (selecting PGAUDIT on the azure.extensions Server Parameter), once you execute the command "CREATE EXTENSION pgaudit" (step 7 in the actual documentation), will get an error message saying the following:
ERROR:  extension "pgaudit" is not allow-listed for "azure_pg_admin" users in Azure Database for PostgreSQL
HINT:  to see the full allow list of extensions, please run: "show azure.extensions;"