Update R script
An extra R script is required: doAzureParallel now requires the rAzureBatch package. If not, the following error occurs:
ERROR: dependency 'rAzureBatch' is not available for package 'doAzureParallel'