Fix the fully qualified class name for the command line
Fix the fully qualified class name for the command line by adding `org.apache.`, otherwise, when trying to find `storm.starter.WordCountTopology`, storm will complain:

    Error: Could not find or load main class storm.starter.WordCountTopology

Because what needs to be passed is

    org.apache.storm.starter.WordCountTopology

I tested this on a:

    Cluster type, HDI version
    Storm on Linux (HDI 3.6)