Add note on required body content.
When manually triggering a function, it appears that a body containing at least `{}` is needed. For example:

Error: `curl --request POST -H "Content-Type:application/json" http://localhost:7071/admin/functions/Foo`
Ok: `curl --request POST -H "Content-Type:application/json" --data '{}' http://localhost:7071/admin/functions/Foo`

I couldn't find a mention of this elsewhere in the docs.