Fix host-header argument for ngrok http command
When running "ngrok http -host-header=localhost 7071", the user will encounter the following error:
ERROR:  unknown shorthand flag: 'o' in -ost-header=localhost

Adding an additional dash so that the argument says "--host-header" will allow the command to function as expected.