Update ingress-controller-install-existing.md
Removed below lines, as this is not required with helm v3. Which comes by default on Azure shell. Helm version 3 remove tiller related configuration, which were required with helm v 2:
Reference internal workitem:  24504496
ICM Reference : 405025905
>>>
Error getting with helm init command, since helm is at version3

helm init --tiller-namespace kube-system --service-account tiller-sa

Error: unknown command "init" for "helm"

Did you mean this?

       lint

Run 'helm --help' for usage.
>>>

Lines deleted 
"""

    - *Kubernetes RBAC enabled* AKS cluster

    ```bash
    kubectl create serviceaccount --namespace kube-system tiller-sa
    kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller-sa
    helm init --tiller-namespace kube-system --service-account tiller-sa
    ```

    - *Kubernetes RBAC disabled* AKS cluster

    ```bash
    helm init
    ```
"""