Update try-v3-python-sdk.md
Fixed indentation which caused error

"document_analysis_client = DocumentAnalysisClient(endpoint=endpoint, credential=AzureKeyCredential(key))
IndentationError: unexpected indent"