Including azureml-sdk as a pip dependency
Adding this dependency ensures that azureml.core and azureml.core Dataset are included when running in AML service.  When excluded AML can error out and state that an azureml module is missing (Usually core and dataset). 

An example error message:
```
ModuleNotFoundError: No module named 'azureml'
```